version: 2.1

orbs:
  terraform: circleci/terraform@1.1.0

workflows: 
  deploy_infrastructure: 
    jobs: 
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate