version: 2.1

orbs:
  terraform: circleci/terraform@1.1.0

workflows: 
  deploy_infrastructure: 
    jobs: 
      - terraform/fmt:
          checkout: true
      - terraform/validate:
          checkout: true
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          persist-workspace: true
          requires:
            - terraform/validate